name: Fossa Compliance Check

on:
  workflow_call:

jobs:
  fossa:
    runs-on: [self-hosted, ubuntu-22-04, regular]

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Set FOSSA API Key
        run: echo "FOSSA_API_KEY=${{ secrets.FOSSA_PUB_API_KEY }}" >> $GITHUB_ENV
        
      - name: Run FOSSA Analysis
        run: fossa analyze
        
      - name: Run FOSSA Test
        run: fossa test
