name: Fossa Compliance Check

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      FOSSA_PUB_API_KEY:
        required: true

jobs:
  fossa:
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]' && github.repository == 'G-Core/FastEdge-sdk-js'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Set FOSSA API Key
        run: echo "FOSSA_API_KEY=${{ secrets.FOSSA_PUB_API_KEY }}" >> $GITHUB_ENV

      - name: Run FOSSA Analysis
        run: fossa analyze

      - name: Run FOSSA Test
        run: fossa test
